version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 25
    commit-message:
      prefix: "fix"
      prefix-development: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "ci"
